// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gradient_cont1d
Rcpp::NumericVector gradient_cont1d(Rcpp::Function f, Rcpp::NumericVector x0, double h);
RcppExport SEXP _gobi_gradient_cont1d(SEXP fSEXP, SEXP x0SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_cont1d(f, x0, h));
    return rcpp_result_gen;
END_RCPP
}
// gradient_cont2d
Rcpp::NumericMatrix gradient_cont2d(Rcpp::Function F, Rcpp::NumericVector x0, double h);
RcppExport SEXP _gobi_gradient_cont2d(SEXP FSEXP, SEXP x0SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type F(FSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_cont2d(F, x0, h));
    return rcpp_result_gen;
END_RCPP
}
// gradient_disc1d
Rcpp::NumericVector gradient_disc1d(Rcpp::NumericVector F, Rcpp::NumericVector h);
RcppExport SEXP _gobi_gradient_disc1d(SEXP FSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type F(FSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_disc1d(F, h));
    return rcpp_result_gen;
END_RCPP
}
// gradient_disc2d
Rcpp::List gradient_disc2d(Rcpp::NumericMatrix F, Rcpp::NumericVector hx, Rcpp::NumericVector hy);
RcppExport SEXP _gobi_gradient_disc2d(SEXP FSEXP, SEXP hxSEXP, SEXP hySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type F(FSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hy(hySEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_disc2d(F, hx, hy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gobi_gradient_cont1d", (DL_FUNC) &_gobi_gradient_cont1d, 3},
    {"_gobi_gradient_cont2d", (DL_FUNC) &_gobi_gradient_cont2d, 3},
    {"_gobi_gradient_disc1d", (DL_FUNC) &_gobi_gradient_disc1d, 2},
    {"_gobi_gradient_disc2d", (DL_FUNC) &_gobi_gradient_disc2d, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gobi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
