# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_cont1d <- function(f, x0, h = 0) {
    .Call(`_gobi_gradient_cont1d`, f, x0, h)
}

gradient_cont2d <- function(F, x0, h = 0) {
    .Call(`_gobi_gradient_cont2d`, F, x0, h)
}

gradient_disc1d <- function(F, h = as.numeric( c(1.0))) {
    .Call(`_gobi_gradient_disc1d`, F, h)
}

gradient_disc2d <- function(F, hx = as.numeric( c(1.0)), hy = as.numeric( c(1.0))) {
    .Call(`_gobi_gradient_disc2d`, F, hx, hy)
}

