# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_scalar <- function(f, x0, h = 0) {
    .Call(`_gobi_gradient_scalar`, f, x0, h)
}

jacobian_vector <- function(F, x0, h = 0) {
    .Call(`_gobi_jacobian_vector`, F, x0, h)
}

gradient_1d <- function(F, h = as.numeric( c(1.0))) {
    .Call(`_gobi_gradient_1d`, F, h)
}

gradient_2d <- function(F, hx = as.numeric( c(1.0)), hy = as.numeric( c(1.0))) {
    .Call(`_gobi_gradient_2d`, F, hx, hy)
}

